# Generated by Django 5.2 on 2025-04-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
    ]
