# Generated by Django 5.2 on 2025-04-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='movie_image_url',
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'movie')},
        ),
    ]
